-- Final Consolidated Schema for Next.js Mastery Guide

-- 1. Modules Table
create table public.modules (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  lessons_count int not null default 0,
  difficulty text check (difficulty in ('Beginner', 'Intermediate', 'Advanced')),
  content_overview text,
  content_code_example text,
  content_topics text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Questions Table
create table public.questions (
  id bigint generated by default as identity primary key,
  module_id bigint references public.modules(id) on delete cascade not null,
  question text not null,
  options text[] not null,
  correct_answer int not null,
  explanation text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Profiles Table
create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text,
  full_name text,
  avatar_url text,
  xp_points int default 0,
  current_streak int default 0,
  last_active_date date,
  hours_learned numeric(10, 2) default 0,
  lessons_completed int default 0,
  quizzes_passed int default 0,
  code_exercises_completed int default 0,
  certificates_earned int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. User Progress Table
create table public.user_progress (
  user_id uuid references auth.users(id) on delete cascade not null,
  module_id bigint references public.modules(id) on delete cascade not null,
  is_completed boolean default false,
  last_accessed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  lesson_details jsonb default '{}'::jsonb,
  exam_passed boolean default false,
  exam_score int,
  primary key (user_id, module_id)
);

-- 5. Notes Table
create table public.notes (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  module_id bigint references public.modules(id) on delete set null,
  lesson_id text,
  title text not null,
  content text,
  tags text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.modules enable row level security;
alter table public.questions enable row level security;
alter table public.profiles enable row level security;
alter table public.user_progress enable row level security;
alter table public.notes enable row level security;

-- Policies

-- Modules
create policy "Modules are viewable by everyone" on public.modules for select using (true);

-- Questions
create policy "Questions are viewable by everyone" on public.questions for select using (true);

-- Profiles
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- User Progress
create policy "Users can view own progress" on public.user_progress for select using (auth.uid() = user_id);
create policy "Users can insert own progress" on public.user_progress for insert with check (auth.uid() = user_id);
create policy "Users can update own progress" on public.user_progress for update using (auth.uid() = user_id);

-- Notes
create policy "Users can view own notes" on public.notes for select using (auth.uid() = user_id);
create policy "Users can insert own notes" on public.notes for insert with check (auth.uid() = user_id);
create policy "Users can update own notes" on public.notes for update using (auth.uid() = user_id);
create policy "Users can delete own notes" on public.notes for delete using (auth.uid() = user_id);

-- Insert Initial Data (Modules)
INSERT INTO public.modules (title, description, lessons_count, difficulty, content_overview, content_code_example, content_topics)
VALUES 
(
  'Introduction to Next.js',
  'Learn the fundamentals of Next.js and why it''s the most popular React framework.',
  5,
  'Beginner',
  'Next.js is a powerful React framework that enables server-side rendering, static site generation, and much more. In this module, you''ll learn the basics and set up your first Next.js application.',
  '// pages/index.js
export default function Home() {
  return <h1>Hello, Next.js!</h1>
}',
  ARRAY['What is Next.js and why use it?', 'Setting up your development environment', 'Creating your first Next.js app', 'Understanding the project structure', 'Running the development server']
),
(
  'Routing & Navigation',
  'Master the file-system based routing mechanism in Next.js.',
  8,
  'Beginner',
  'Next.js uses a file-system based router built on the concept of pages. When a file is added to the pages directory, it''s automatically available as a route.',
  '// pages/about.js maps to /about
import Link from ''next/link''

export default function About() {
  return (
    <div>
      <h1>About Us</h1>
      <Link href="/">Back home</Link>
    </div>
  )
}',
  ARRAY['File-system routing explained', 'Nested routes', 'Dynamic routes with [param]', 'Linking between pages with <Link>', 'useRouter hook']
);

-- Consider adding more module inserts here matching courseData.ts if desired.
