-- Create modules table
CREATE TABLE IF NOT EXISTS public.modules (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    lessons_count INTEGER NOT NULL DEFAULT 0,
    difficulty TEXT,
    content_overview TEXT,
    content_code_example TEXT,
    content_topics TEXT[],
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create questions table
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    module_id BIGINT REFERENCES public.modules(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    options TEXT[] NOT NULL,
    correct_answer INTEGER NOT NULL,
    explanation TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create user_progress table
CREATE TABLE IF NOT EXISTS public.user_progress (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    module_id BIGINT REFERENCES public.modules(id) ON DELETE CASCADE,
    is_completed BOOLEAN DEFAULT FALSE,
    last_accessed_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (user_id, module_id)
);

-- Enable Row Level Security
ALTER TABLE public.modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;

-- Create Policies
-- Modules and Questions are readable by everyone (or authenticated users)
CREATE POLICY "Modules are viewable by everyone" ON public.modules FOR SELECT USING (true);
CREATE POLICY "Questions are viewable by everyone" ON public.questions FOR SELECT USING (true);

-- User Progress is only for the user
CREATE POLICY "Users can view their own progress" ON public.user_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert/update their own progress" ON public.user_progress FOR ALL USING (auth.uid() = user_id);

-- Seed Data for Modules
INSERT INTO public.modules (id, title, description, lessons_count, difficulty, content_overview, content_code_example, content_topics)
VALUES
(1, 'Introduction to Next.js', 'Learn the fundamentals of Next.js and why it''s the most popular React framework.', 5, 'Beginner', 'Next.js is a powerful React framework that enables server-side rendering, static site generation, and much more. In this module, you''ll learn the basics and set up your first Next.js application.', '// pages/index.js
export default function Home() {
  return (
    <div>
      <h1>Welcome to Next.js!</h1>
      <p>Your first Next.js application</p>
    </div>
  )
}', ARRAY['What is Next.js and why use it?', 'Setting up your development environment', 'Creating your first Next.js app', 'Understanding the project structure', 'Running and building your app']),

(2, 'Pages and Routing', 'Master Next.js file-based routing system and learn how to create dynamic routes.', 6, 'Beginner', 'Next.js uses a file-based routing system that makes creating pages incredibly simple. Learn how to create static and dynamic routes.', '// pages/blog/[slug].js
import { useRouter } from ''next/router''

export default function BlogPost() {
  const router = useRouter()
  const { slug } = router.query

  return <h1>Post: {slug}</h1>
}', ARRAY['File-based routing basics', 'Creating static pages', 'Dynamic routes with [id]', 'Nested routes and layouts', 'Catch-all routes', 'Programmatic navigation']),

(3, 'Data Fetching Methods', 'Explore getStaticProps, getServerSideProps, and other data fetching techniques.', 7, 'Intermediate', 'Next.js provides multiple ways to fetch data depending on your needs. Learn when and how to use each method.', '// pages/posts.js
export async function getStaticProps() {
  const res = await fetch(''https://api.example.com/posts'')
  const posts = await res.json()

  return {
    props: { posts },
    revalidate: 60 // ISR: regenerate every 60 seconds
  }
}

export default function Posts({ posts }) {
  return (
    <div>
      {posts.map(post => (
        <article key={post.id}>
          <h2>{post.title}</h2>
        </article>
      ))}
    </div>
  )
}', ARRAY['Understanding different rendering strategies', 'Static Generation with getStaticProps', 'Server-side Rendering with getServerSideProps', 'Incremental Static Regeneration (ISR)', 'Client-side data fetching', 'SWR and data fetching patterns', 'API routes for backend logic']),

(4, 'API Routes', 'Build serverless API endpoints directly in your Next.js application.', 5, 'Intermediate', 'Next.js allows you to create API routes as serverless functions. Perfect for building backend functionality without a separate server.', '// pages/api/users.js
export default async function handler(req, res) {
  if (req.method === ''GET'') {
    const users = await fetchUsers()
    res.status(200).json(users)
  } else if (req.method === ''POST'') {
    const newUser = await createUser(req.body)
    res.status(201).json(newUser)
  } else {
    res.status(405).json({ message: ''Method not allowed'' })
  }
}', ARRAY['Creating API routes', 'Handling different HTTP methods', 'Request and response handling', 'API middleware', 'Connecting to databases']),

(5, 'Styling in Next.js', 'Learn CSS Modules, Styled Components, Tailwind CSS, and other styling approaches.', 6, 'Beginner', 'Next.js supports various styling solutions. Choose the one that fits your project best.', '// Using CSS Modules
import styles from ''./Button.module.css''

export default function Button() {
  return <button className={styles.primary}>Click me</button>
}

// Tailwind CSS
export default function Card() {
  return (
    <div className="rounded-lg shadow-lg p-6 bg-white">
      <h2 className="text-2xl font-bold">Card Title</h2>
    </div>
  )
}', ARRAY['Global styles and CSS imports', 'CSS Modules for component-scoped styles', 'Setting up Tailwind CSS', 'Styled Components and CSS-in-JS', 'Sass/SCSS support', 'Font optimization with next/font']),

(6, 'Image Optimization', 'Use Next.js Image component for automatic image optimization and lazy loading.', 4, 'Beginner', 'Next.js provides powerful image optimization out of the box with the Image component.', 'import Image from ''next/image''

export default function Avatar() {
  return (
    <Image
      src="/profile.jpg"
      alt="Profile picture"
      width={500}
      height={500}
      priority
      className="rounded-full"
    />
  )
}', ARRAY['next/image component basics', 'Responsive images', 'Image sizing and layouts', 'External image optimization']),

(7, 'App Router (Next.js 13+)', 'Explore the new App Router with React Server Components and Layouts.', 8, 'Advanced', 'The App Router is the future of Next.js, introducing Server Components, improved layouts, and more.', '// app/layout.js (Root Layout)
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>Navigation</nav>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  )
}

// app/page.js (Server Component by default)
async function getData() {
  const res = await fetch(''https://api.example.com/data'')
  return res.json()
}

export default async function Page() {
  const data = await getData()
  return <main>{data.title}</main>
}', ARRAY['App directory structure', 'Server vs Client Components', 'Layouts and templates', 'Loading and error states', 'Parallel routes', 'Intercepting routes', 'Route handlers', 'Streaming and Suspense']),

(8, 'Authentication & Authorization', 'Implement secure authentication with NextAuth.js and protect your routes.', 6, 'Advanced', 'Learn how to add authentication to your Next.js app using NextAuth.js and other popular solutions.', '// pages/api/auth/[...nextauth].js
import NextAuth from ''next-auth''
import GoogleProvider from ''next-auth/providers/google''

export default NextAuth({
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
    }),
  ],
  callbacks: {
    async session({ session, token }) {
      session.user.id = token.sub
      return session
    }
  }
})', ARRAY['Setting up NextAuth.js', 'OAuth providers (Google, GitHub, etc.)', 'Email/password authentication', 'Session management', 'Protected routes and middleware', 'Role-based access control']),

(9, 'Database Integration', 'Connect to databases like PostgreSQL, MongoDB, and use Prisma ORM.', 7, 'Advanced', 'Learn how to integrate databases into your Next.js application for persistent data storage.', '// lib/prisma.js
import { PrismaClient } from ''@prisma/client''

const globalForPrisma = global as unknown as { prisma: PrismaClient }

export const prisma = globalForPrisma.prisma || new PrismaClient()

if (process.env.NODE_ENV !== ''production'') globalForPrisma.prisma = prisma

// pages/api/posts.js
import { prisma } from ''../../lib/prisma''

export default async function handler(req, res) {
  const posts = await prisma.post.findMany({
    include: { author: true }
  })
  res.json(posts)
}', ARRAY['Choosing the right database', 'Setting up Prisma ORM', 'Database schema design', 'CRUD operations', 'Database migrations', 'Connection pooling', 'Using MongoDB with Next.js']),

(10, 'Deployment & Performance', 'Deploy to Vercel, optimize performance, and implement best practices.', 6, 'Advanced', 'Learn how to deploy your Next.js application and optimize it for production.', '// next.config.js
module.exports = {
  images: {
    domains: [''example.com''],
  },
  i18n: {
    locales: [''en'', ''fr'', ''de''],
    defaultLocale: ''en'',
  },
  headers: async () => {
    return [
      {
        source: ''/:path*'',
        headers: [
          {
            key: ''X-DNS-Prefetch-Control'',
            value: ''on''
          }
        ]
      }
    ]
  }
}', ARRAY['Deploying to Vercel', 'Environment variables', 'Performance optimization techniques', 'Monitoring and analytics', 'SEO best practices', 'Edge functions and middleware'])
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description;

-- Reset IDENTITY to avoid primary key collisions if manually inserting later
SELECT setval('modules_id_seq', (SELECT MAX(id) FROM public.modules));


-- Seed Data for Questions
-- Module 1 Questions
INSERT INTO public.questions (module_id, question, options, correct_answer, explanation)
VALUES
(1, 'What command is used to create a new Next.js project?', ARRAY['npm init next', 'npx create-next-app', 'npm install next', 'next new project'], 1, 'npx create-next-app is the official command to scaffold a new Next.js project with all necessary configurations.'),
(1, 'Which folder structure is used in Next.js 13+ for the App Router?', ARRAY['pages/', 'src/', 'app/', 'routes/'], 2, 'The app/ directory is the new convention in Next.js 13+ for the App Router, replacing the pages/ directory.'),
(1, 'What is the default rendering strategy in Next.js 13+ App Router?', ARRAY['Client-side rendering', 'Static generation', 'Server Components', 'Incremental Static Regeneration'], 2, 'By default, all components in the App Router are Server Components, which render on the server.');

-- Module 2 Questions
INSERT INTO public.questions (module_id, question, options, correct_answer, explanation)
VALUES
(2, 'How do you define a dynamic route in Next.js App Router?', ARRAY['[param]/page.tsx', ':param/page.tsx', '{param}/page.tsx', 'param?/page.tsx'], 0, 'Dynamic segments are created by wrapping a folder name in square brackets: [param]'),
(2, 'What file is used to define route layouts in Next.js?', ARRAY['_layout.tsx', 'layout.tsx', 'Layout.tsx', 'template.tsx'], 1, 'layout.tsx is the special file name for defining shared layouts in the App Router.'),
(2, 'How do you create a loading state for a route?', ARRAY['loading.tsx', '_loading.tsx', 'Loading.tsx', 'loader.tsx'], 0, 'loading.tsx is automatically shown while route content is loading, leveraging React Suspense.');
