-- EMERGENCY FIX: V2 Schema
-- Renaming tables to force fresh API cache registration.

-- 1. New Tables with "course_" prefix
create table public.course_modules (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  lessons_count int not null default 0,
  difficulty text check (difficulty in ('Beginner', 'Intermediate', 'Advanced')),
  content_overview text,
  content_code_example text,
  content_topics text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.course_questions (
  id bigint generated by default as identity primary key,
  module_id bigint references public.course_modules(id) on delete cascade not null,
  question text not null,
  options text[] not null,
  correct_answer int not null,
  explanation text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.course_progress (
  user_id uuid references auth.users(id) on delete cascade not null,
  module_id bigint references public.course_modules(id) on delete cascade not null,
  is_completed boolean default false,
  last_accessed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  lesson_details jsonb default '{}'::jsonb,
  exam_passed boolean default false,
  exam_score int,
  primary key (user_id, module_id)
);

-- 2. Enable RLS
alter table public.course_modules enable row level security;
alter table public.course_questions enable row level security;
alter table public.course_progress enable row level security;

-- 3. Policies
create policy "Public modules" on public.course_modules for select using (true);
create policy "Public questions" on public.course_questions for select using (true);

create policy "User progress view" on public.course_progress for select using (auth.uid() = user_id);
create policy "User progress insert" on public.course_progress for insert with check (auth.uid() = user_id);
create policy "User progress update" on public.course_progress for update using (auth.uid() = user_id);

-- 4. Seed Data
INSERT INTO public.course_modules (title, description, lessons_count, difficulty, content_overview, content_code_example, content_topics)
VALUES 
(
  'Introduction to Next.js',
  'Learn the fundamentals.', 
  5, 
  'Beginner', 
  'Intro contents...', 
  '// Code', 
  ARRAY['Intro', 'Setup']
),
(
  'Routing Pattern',
  'Master file-based routing.', 
  8, 
  'Beginner', 
  'Routing contents...', 
  '// Code', 
  ARRAY['Routing', 'Dynamic Routes']
);

-- Force reload just in case
NOTIFY pgrst, 'reload config';
