-- FINAL V2 SETUP SCRIPT
-- RUN THIS SCRIPT TO FIX ALL API ERRORS.
-- It works by creating new tables (v2) that Bypass the stuck cache.

-- 1. CLEANUP (Drop V2 tables if they partially exist to restart fresh)
DROP TABLE IF EXISTS public.course_questions CASCADE;
DROP TABLE IF EXISTS public.course_progress CASCADE;
DROP TABLE IF EXISTS public.course_notes CASCADE;
DROP TABLE IF EXISTS public.course_modules CASCADE;
DROP TABLE IF EXISTS public.course_profiles CASCADE;

-- 2. CREATE TABLES

-- Modules
create table public.course_modules (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  lessons_count int not null default 0,
  difficulty text check (difficulty in ('Beginner', 'Intermediate', 'Advanced')),
  content_overview text,
  content_code_example text,
  content_topics text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Questions
create table public.course_questions (
  id bigint generated by default as identity primary key,
  module_id bigint references public.course_modules(id) on delete cascade not null,
  question text not null,
  options text[] not null,
  correct_answer int not null,
  explanation text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Profiles (Stats & Leaderboard)
create table public.course_profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  full_name text,
  avatar_url text,
  xp_points int default 0,
  current_streak int default 0,
  hours_learned float default 0,
  lessons_completed int default 0,
  quizzes_passed int default 0,
  certificates_earned int default 0,
  code_exercises_completed int default 0,
  last_active_date date default CURRENT_DATE,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Progress
create table public.course_progress (
  user_id uuid references auth.users(id) on delete cascade not null,
  module_id bigint references public.course_modules(id) on delete cascade not null,
  is_completed boolean default false,
  last_accessed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  lesson_details jsonb default '{}'::jsonb,
  exam_passed boolean default false,
  exam_score int,
  primary key (user_id, module_id)
);

-- Notes
create table public.course_notes (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) not null,
  module_id bigint references public.course_modules(id),
  lesson_id text,
  title text not null,
  content text,
  tags text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ENABLE SECURITY (RLS)

alter table public.course_modules enable row level security;
alter table public.course_questions enable row level security;
alter table public.course_profiles enable row level security;
alter table public.course_progress enable row level security;
alter table public.course_notes enable row level security;

-- 4. POLICIES

-- Modules (Public)
create policy "Public modules" on public.course_modules for select using (true);
-- Questions (Public)
create policy "Public questions" on public.course_questions for select using (true);

-- Profiles (Public Read, Self Update)
create policy "Public profiles" on public.course_profiles for select using (true);
create policy "Users can update own profile" on public.course_profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on public.course_profiles for insert with check (auth.uid() = id);

-- Progress (Self Only)
create policy "User progress view" on public.course_progress for select using (auth.uid() = user_id);
create policy "User progress insert" on public.course_progress for insert with check (auth.uid() = user_id);
create policy "User progress update" on public.course_progress for update using (auth.uid() = user_id);

-- Notes (Self Only)
create policy "User notes view" on public.course_notes for select using (auth.uid() = user_id);
create policy "User notes insert" on public.course_notes for insert with check (auth.uid() = user_id);
create policy "User notes update" on public.course_notes for update using (auth.uid() = user_id);
create policy "User notes delete" on public.course_notes for delete using (auth.uid() = user_id);

-- 5. SEED DATA

INSERT INTO public.course_modules (title, description, lessons_count, difficulty, content_overview, content_code_example, content_topics)
VALUES 
(
  'Introduction to Next.js',
  'Learn the fundamentals of Next.js and why it''s the most popular React framework.',
  5,
  'Beginner',
  'Next.js is a powerful React framework that enables server-side rendering...',
  'export default function Home() { return <h1>Hello</h1> }',
  ARRAY['Intro', 'Setup', 'First App']
),
(
  'Routing & Navigation',
  'Master file-system based routing.',
  8,
  'Beginner',
  'Next.js uses a file-system based router...',
  'import Link from "next/link"',
  ARRAY['Dynamic Routes', 'Nested Routes']
),
(
  'Server Components',
  'Understanding React Server Components (RSC).',
  6,
  'Intermediate',
  'Server Components allow you to write UI that can be rendered on the server.',
  'async function getData() { const res = await fetch(...) }',
  ARRAY['RSC vs Client', 'Streaming']
);

-- Force Reload
NOTIFY pgrst, 'reload config';
