-- FINAL FIX: Recreate Modules Table
-- This script deletes the modules table and recreates it to force the API to see it.

-- 1. Drop existing tables (Cascades to questions and progress)
DROP TABLE IF EXISTS public.modules CASCADE;

-- 2. Recreate Modules Table
create table public.modules (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  lessons_count int not null default 0,
  difficulty text check (difficulty in ('Beginner', 'Intermediate', 'Advanced')),
  content_overview text,
  content_code_example text,
  content_topics text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Enable RLS
alter table public.modules enable row level security;
create policy "Modules are viewable by everyone" on public.modules for select using (true);

-- 4. Re-Insert Data
INSERT INTO public.modules (title, description, lessons_count, difficulty, content_overview, content_code_example, content_topics)
VALUES 
(
  'Introduction to Next.js',
  'Learn the fundamentals of Next.js and why it''s the most popular React framework.',
  5,
  'Beginner',
  'Next.js is a powerful React framework that enables server-side rendering, static site generation, and much more.',
  '// pages/index.js
export default function Home() {
  return <h1>Hello, Next.js!</h1>
}',
  ARRAY['What is Next.js?', 'Setting up environment', 'First App', 'Project Structure']
),
(
  'Routing & Navigation',
  'Master the file-system based routing mechanism.',
  8,
  'Beginner',
  'Next.js uses a file-system based router built on the concept of pages.',
  'import Link from ''next/link''
export default function Nav() {
  return <Link href="/about">About</Link>
}',
  ARRAY['File-system routing', 'Nested routes', 'Dynamic routes', 'next/link']
),
(
  'API Routes',
  'Build serverless APIs with Next.js.',
  5,
  'Intermediate',
  'Create API endpoints as Node.js serverless functions.',
  'export default function handler(req, res) {
  res.status(200).json({ name: ''John Doe'' })
}',
  ARRAY['API Routing', 'Request Helpers', 'Dynamic API Routes']
);

-- 5. Force Config Reload one last time
NOTIFY pgrst, 'reload config';
